# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('sequence_name', models.CharField(blank=True, max_length=255)),
                ('sequence_order', models.PositiveIntegerField(blank=True, default=0)),
                ('concepts', models.TextField(blank=True)),
                ('previous_knowledge', models.TextField(blank=True)),
                ('student_artifact', models.CharField(blank=True, max_length=255)),
                ('student_artifact_description', models.TextField(blank=True)),
                ('standards_framework', models.CharField(blank=True, max_length=255)),
                ('standards_category', models.CharField(blank=True, max_length=255)),
                ('standards_subcategory', models.CharField(blank=True, max_length=255)),
                ('standards_refnumber', models.CharField(blank=True, max_length=255)),
                ('standards_description', models.CharField(blank=True, max_length=255)),
                ('cs_objectives', models.TextField(blank=True)),
                ('subject_objectives', models.TextField(blank=True)),
                ('devices_required', models.TextField(blank=True)),
                ('devices_alternate', models.TextField(blank=True)),
                ('devices_optional', models.TextField(blank=True)),
                ('unplugged_required', models.TextField(blank=True)),
                ('unplugged_alternate', models.TextField(blank=True)),
                ('unplugged_optional', models.TextField(blank=True)),
                ('lesson_objective', models.TextField(blank=True)),
                ('lesson_aim', models.TextField(blank=True)),
                ('lesson_mini_description', models.TextField(blank=True)),
                ('lesson_independent_time_description', models.TextField(blank=True)),
                ('lesson_share', models.TextField(blank=True)),
                ('reflection_questions', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
