# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20161220_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='concepts',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='cs_objectives',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='devices_alternate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='devices_optional',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='devices_required',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lesson_aim',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lesson_independent_time_description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lesson_mini_description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lesson_objective',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lesson_share',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='previous_knowledge',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='reflection_questions',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='sequence_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='sequence_order',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='standards_category',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='standards_description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='standards_framework',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='standards_refnumber',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='standards_subcategory',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='student_artifact',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='student_artifact_description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subject_objectives',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='unplugged_alternate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='unplugged_optional',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='unplugged_required',
        ),
        migrations.AddField(
            model_name='activity',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
