# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20161220_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='google_file_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
