# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 19:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_google_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='html_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
