# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='plain_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
