# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_plain_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='grade_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subject_name',
        ),
    ]
