# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20170306_0325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
