# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_activity_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='software',
        ),
    ]
