# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
