# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_auto_20170518_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='activities',
            field=models.ManyToManyField(blank=True, to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='activities.ResourceTag'),
        ),
    ]
