# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_resource_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
