# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_unittags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitTags',
            new_name='UnitTag',
        ),
    ]
