# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_auto_20170726_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Subject'),
        ),
    ]
